apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules-watchdog
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus

data:
  watchdog.yml: |
    groups:
      - name: sf1-watchdog
        rules:
          - alert: Watchdog
            expr: vector(1)
            labels:
              severity: info
            annotations:
              summary: "Watchdog"
              description: "Dauerfeuernder Heartbeat zum Test der Alert-Pipeline"