apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: blackbox-exporter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: 9115