apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: s3-backup
  namespace: backup
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID:     "AgF..."
    AWS_SECRET_ACCESS_KEY: "AgG..."
    AWS_DEFAULT_REGION:    "AgH..."
    S3_BUCKET:             "AgI..."
  template:
    metadata:
      name: s3-backup
      namespace: backup
    type: Opaque