apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: api-secrets
  namespace: default
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
spec:
  encryptedData:
    MONGODB_URI: "AgB..."        # verschlÃ¼sselt
    JWT_SECRET:   "AgC..."
    SMTP_USER:    "AgD..."
    SMTP_PASS:    "AgE..."
  template:
    metadata:
      name: api-secrets
      namespace: default
    type: Opaque