apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-receivers
  namespace: monitoring
spec:
  encryptedData:
    SLACK_WEBHOOK_URL: "AgJ..."
    ALERT_EMAIL_USER:  "AgK..."
    ALERT_EMAIL_PASS:  "AgL..."
  template:
    metadata:
      name: alertmanager-receivers
      namespace: monitoring
    type: Opaque