apiVersion: v1
kind: Service
metadata:
name: sf1-scraper-metrics
namespace: default
labels:
app: sf1-scraper
role: worker
spec:
selector:
app: sf1-scraper
role: worker
ports:
- name: metrics
port: 9309
targetPort: metrics
type: ClusterIP