apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: sf1
stringData:
  jwt: 8f9a4c4c5a2e4b66a7d1c2b19c9a0f22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sf1-backend
  namespace: sf1
spec:
  replicas: 2
  selector:
    matchLabels: { app: sf1-backend }
  template:
    metadata:
      labels: { app: sf1-backend }
    spec:
      containers:
      - name: api
        image: ghcr.io/callie84/sf1-backend:main
        ports: [{containerPort: 3000}]
        env:
        - name: MONGO_URI
          value: mongodb://sfapp:App!Pass2025@mongo.sf1.svc.cluster.local:27017/sf1?authSource=admin
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: jwt
---
apiVersion: v1
kind: Service
metadata:
  name: sf1-backend
  namespace: sf1
spec:
  selector: { app: sf1-backend }
  ports:
  - port: 80
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sf1-backend
  namespace: sf1
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
  - hosts: ["api.seedfinderpro.de"]
    secretName: api-seedfinderpro-tls
  rules:
  - host: api.seedfinderpro.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sf1-backend
            port:
              number: 80