apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sf1-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "caddy"
    caddy.ingress.kubernetes.io/tls: "internal"
spec:
  rules:
    - host: seedfinderpro.de
      http:
        paths:
          - path: /api/price
            pathType: Prefix
            backend:
              service:
                name: price-service
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sf1-backend
                port:
                  number: 4000
  tls:
    - hosts:
        - seedfinderpro.de
      secretName: sf1-tls
