apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-rqs
  namespace: sf1
spec:
  schedule: "30 */6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: scraper
            image: ghcr.io/callie84/sf1-scraper:main
            env:
            - name: TARGET
              value: rqs
            - name: MONGO_URI
              value: mongodb://sfapp:App!Pass2025@mongo.sf1.svc.cluster.local:27017/sf1?authSource=admin