apiVersion: v1
kind: Secret
metadata:
  name: sf1-backend-env
  namespace: default
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongo.default.svc.cluster.local:27017/sf1"
  JWT_SECRET: "changeme-please"
---
apiVersion: v1
kind: Secret
metadata:
  name: sf1-price-service-env
  namespace: default
type: Opaque
stringData:
  NODE_ENV: "production"
