apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plausible
  namespace: analytics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: sf1-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts: ["analytics.seedfinderpro.de"]
    secretName: analytics-seedfinderpro-tls
  rules:
  - host: analytics.seedfinderpro.de
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: plausible
            port:
              number: 80