apiVersion: v1
kind: Secret
metadata:
  name: backup-s3
  namespace: backup
stringData:
  AWS_ACCESS_KEY_ID: "AKIAEXAMPLE12345"
  AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  AWS_S3_ENDPOINT: "https://s3.eu-central-1.amazonaws.com"
  AWS_S3_BUCKET: "sf1-backups"
  RESTIC_PASSWORD: "ChangeThisNow#2025"