apiVersion: v1
kind: Secret
metadata:
  name: backup-rsync
  namespace: backup
stringData:
  RSYNC_USER: "backup"
  RSYNC_HOST: "152.53.252.68"
  RSYNC_PATH: "/srv/sf1_backups"
  RSYNC_PORT: "22"
  RSYNC_SSH_PRIVATE_KEY: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    CHANGE-THIS-KEY
    -----END OPENSSH PRIVATE KEY-----