name: docker-price-service

on:
  push:
    branches: [ feat/vite, main ]
    paths:
      - "apps/price-service/**"
      - "Dockerfile.price-service"
      - ".github/workflows/docker-price-service.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.price-service
          push: false
          tags: seedfinderpro/price-service:latest
